// generated by scripts/build_assets.py — do not edit
export const PHOTOS = {
 "hezar-rose": {
  "w": 1179,
  "h": 1560,
  "ratio": 0.7558,
  "focal": 0.42,
  "widths": [
   400,
   760,
   1140
  ],
  "blur": "data:image/webp;base64,UklGRsgAAABXRUJQVlA4ILwAAADQBQCdASoYACAAPslOo0snpCMhsBgMAPAZCWQAxnwwG0WgWmNlH46BR8oYP8Mcnflpen5MA8d0AP7gBdKr+zYc2+MltxwKLg8tIPA1I4pI8ImkNWla4VZxTEtJW/mo4lp9550Yu6h0Xz5NuTxh4h6soJXbe5Kuk4WGrzda/JaIOrjNi9FVZrPypoknL7fR0JQpuR5ieUu+mZgxjtCBC9jKkuPl4iF5E6bD/rtIU0Z+UqoItqwFDEISjgAAAA=="
 },
 "arghavan": {
  "w": 1179,
  "h": 1560,
  "ratio": 0.7558,
  "focal": 0.45,
  "widths": [
   400,
   760,
   1140
  ],
  "blur": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAABQBQCdASoYACAAPslUo0snpKMhsAgA8BkJQBSQA3SjDPm/flsEc+waXveGou70SSo36YAA/vBB7ZT1cLfIGy+xYNyj96eOBmi+WGjAHepXD8iUQtAg8h4CLQjBsLF8iwSjg/4WdZlHtOQ8W9hJ7QFs4AYNPGB1tw6bQTuF+fozPgjT0ozaGbnfDXOOKSBrZ3kVxx1lxaDyFnEnQFtoEDIasAA="
 },
 "aftab": {
  "w": 1179,
  "h": 1893,
  "ratio": 0.6228,
  "focal": 0.42,
  "widths": [
   400,
   760,
   1140
  ],
  "blur": "data:image/webp;base64,UklGRugAAABXRUJQVlA4INwAAACQBgCdASoYACcAPslUpUsnpKOhqqwA8BkJQBftZfg/LhcysUbU+DRw7de9Wet2jXW4EBVXFV89GcMHMBtAAP7nQI00Syg/nIjLTV+cqK6eU/MevJRM7cck3iSc+WbjyXwMmTONRWQYlm6v/szcWDr1TdmPNZUaQZJsLaaEfg3EC/fJhXDsHEbzkGirZKLdLXEIe9exlP+KCp/VhjyJGbYDjFXU7iVPqoCAytVNMzwmn+W0XlkRSeiWfoycg1UUEcIQTOGtiJmbNSUMwRHoC11AwNwM7qa/mK49M0IA"
 },
 "sahar": {
  "w": 1179,
  "h": 1453,
  "ratio": 0.8114,
  "focal": 0.48,
  "widths": [
   400,
   760,
   1140
  ],
  "blur": "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAACwBQCdASoYAB4APslWpU0npKOiMBgIAPAZCWcAygAPL8rlVyKf1RFSJeMCI88ne4n7K6ErbQAAzWhjPedEIcjq4/0bbtbGXbJespJLFBujjsAYRZKKsAVEOn/jS1rAZaBo3jrJTIkRw0ZDTxtCTcoxxIbONgldXwpwpS/CnZzcVeSGHksW/gfgI82RsOtFv/Y5VY61yp8g+TIndH4VL3OTboOTiZcdQTubMwmvl4AAAA=="
 },
 "banafsheh": {
  "w": 1179,
  "h": 1558,
  "ratio": 0.7567,
  "focal": 0.52,
  "widths": [
   400,
   760,
   1140
  ],
  "blur": "data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAABQBQCdASoYACAAPslYqE0npSQiKAqo8BkJYwC3uGlfiyWjJgcuTVjaifEYrFwlNTByGdAA/v0BUpaRMogGPfFo9ZJPbgw1RPyOwhuwTbcn2ihBY6JWZJrNDkC85guXXqdmst4+JLz3Davuhgnj2dpz2UiGgpX78sRvjNHIOLX4t6doMTdq0E/TuYyLnhcNlKOHyDKtC7vhVk1gkrwDfY7B63JklRiP52hWYc7pUakfQAAA"
 },
 "nilgoon": {
  "w": 1179,
  "h": 496,
  "ratio": 2.377,
  "focal": 0.5,
  "widths": [
   400,
   760,
   1140
  ],
  "blur": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAAAwBACdASoYAAoAPslUoksnpKMhsAgA8BkJYwC26DZBzskf6Q7SAAAU6AAA/l/Xqmcw84QSVJHQ9a9cwarLIrJd4X2i9/24JBW9fv0rPF15Xs2eRwJ4EstFawZnSKoifZh9y+ZzUZr8rHf0cJTDHP+QYAA="
 },
 "shahd": {
  "w": 1179,
  "h": 1905,
  "ratio": 0.6189,
  "focal": 0.45,
  "widths": [
   400,
   760,
   1140
  ],
  "blur": "data:image/webp;base64,UklGRk4BAABXRUJQVlA4IEIBAAAwBwCdASoYACcAPslao00npSMiKqoA8BkJagCdOUFR/idQXAaX+W2pC9lKeXSG0gCzP3le5DL7MDVPEACdR7V+qQAA/piwICzPehrIE47MjJ9EzmOelu70fKQvIu6aONpskszsvPQyuhotu6Xdk9sGw38MdqNYMft0+QnEeuPBdyTPZpORidXoAEHQes9gHsBynNV8uEI/pu091st5Fev/85Atj+db8KQgSbnVx3bsYIUbwsGR8He82uXN0q7Qiwx5NhTNqiIFgFg3U9qYJW2QhS8mIeOP7Jdu5UDsDOGxhxJyCb9Oqt9Ug8td9+Yrxvb70sxFSzw9/eAX0UqnvuOBSfnpn0Ryhb4Z+aQDzpA/tW/z2l698UQRMjR7gsLn1aKfv/ZeI2VCdrKbzAFRQBbLEzay+xM+TP83AtSQyI488AAA"
 }
};
